services:
  tornado-app:
    image: ${TORNADO_IMAGE:-ai-assist-tornado:${IMAGE_TAG:-latest}}
    restart: always
    environment:
      - ENVIRONMENT=production
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  flask-app:
    image: ${FLASK_IMAGE:-ai-assist-flask:${IMAGE_TAG:-latest}}
    restart: always
    environment:
      - TORNADO_BASE_URL=http://tornado-app:8888
      - ENVIRONMENT=production
      - FLASK_ENV=production
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nginx:
    restart: always
    ports:
      - "80:80"
      - "443:443"  # HTTPS for production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M