services:
  tornado-app:
    image: ${TORNADO_IMAGE:-ai-assist-tornado:${IMAGE_TAG:-ref}}
    restart: always
    environment:
      - ENVIRONMENT=ref
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  flask-app:
    image: ${FLASK_IMAGE:-ai-assist-flask:${IMAGE_TAG:-ref}}
    restart: always
    environment:
      - TORNADO_BASE_URL=http://tornado-app:8888
      - ENVIRONMENT=ref
      - FLASK_ENV=staging
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M