services:
  tornado-app:
    image: ${TORNADO_IMAGE:-ai-assist-tornado:latest}
    build:
      context: .
      dockerfile: tornado_app/Dockerfile
      tags:
        - ai-assist-tornado:latest
        - ai-assist-tornado:${IMAGE_TAG:-latest}
    expose:
      - "8888"
    container_name: tornado-container
    restart: unless-stopped
    networks:
      - webapps

  flask-app:
    image: ${FLASK_IMAGE:-ai-assist-flask:latest}
    build:
      context: .
      dockerfile: flask_app/Dockerfile
      tags:
        - ai-assist-flask:latest
        - ai-assist-flask:${IMAGE_TAG:-latest}
    expose:
      - "5000"
    container_name: flask-container
    restart: unless-stopped
    depends_on:
      - tornado-app
    environment:
      - TORNADO_BASE_URL=http://tornado-app:8888
    networks:
      - webapps

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
      - tornado-app
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      - webapps

networks:
  webapps:
    driver: bridge